# Generated by Django 5.0.6 on 2024-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalfinance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="allocation_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
