# Generated by Django 5.0.6 on 2024-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalfinance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fmodel",
            name="created",
            field=models.DateField(auto_now=True),
        ),
    ]
