# Generated by Django 5.0.6 on 2024-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalfinance", "0003_fmodel_unique_fmodel_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fmodel",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
