# Generated by Django 5.0.6 on 2024-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalfinance", "0004_alter_fmodel_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepage",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
